## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np
print (np.__version__)

1.16.2


Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
a = np.array([0]*10)
b = np.zeros(10,dtype=int)
print(a, b)


[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]


Создать вектор размера 10, заполненный единицами

In [3]:
a = np.array([1]*10)
b = np.ones(10,dtype=int)
print(a, b)


[1 1 1 1 1 1 1 1 1 1] [1 1 1 1 1 1 1 1 1 1]


Создать вектор размера 10, заполненный числом 2.5

In [4]:
a = np.array([2.5]*10)
b = np.full(10,2.5)
print(a, b)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5] [2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [5]:
b = np.zeros(10,dtype=int)
b[4]=1
print(b)

[0 0 0 0 1 0 0 0 0 0]


Развернуть вектор (первый становится последним)

In [6]:
a = np.arange(10)
print(np.flip(a))
print(a[::-1])


[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [7]:
a = np.fromfunction(lambda x,y:x*3+y, (3,3), dtype=int)
b = np.arange(9).reshape(3,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
a=np.array([1,2,0,0,4,0])
for x in a:
    if x!=0: print (x)

1
2
4


Создать 3x3 единичную матрицу

In [9]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Создать массив 3x3x3 со случайными значениями

In [10]:
np.random.randint(1,10,(3,3,3))

array([[[6, 9, 8],
        [3, 8, 3],
        [1, 8, 7]],

       [[8, 3, 2],
        [6, 6, 4],
        [3, 3, 9]],

       [[6, 9, 7],
        [9, 6, 8],
        [1, 2, 1]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [11]:
a = np.random.randint(0,100,30)
print (a)
print (a.mean())

[14 64 64 42 89  9 18 41 56 22 95 94 97 83 20 25 37 15 50 84 83 90 17 21
 83 90 19 14 43 67]
51.53333333333333


Перемножить матрицы 5x3 и 3x2

In [12]:
a = np.random.randint(0,10,(5,3))
print (a)
b = np.random.randint(0,10,(3,2))
print (b)
c = a@b
print (c)

[[1 7 2]
 [8 8 2]
 [8 0 8]
 [5 9 8]
 [9 4 0]]
[[9 1]
 [4 9]
 [3 5]]
[[ 43  74]
 [110  90]
 [ 96  48]
 [105 126]
 [ 97  45]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [13]:
a = np.linspace(0,1,11,False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


Заменить максимальный элемент на ноль

In [14]:
a = np.random.random(100)
print(a)
print(a.argmax())
a[a.argmax()] = 0
print(a)


[0.05417442 0.48982794 0.72123087 0.35993572 0.23003384 0.69246951
 0.1300347  0.17979566 0.20571004 0.14281582 0.22289909 0.6508367
 0.69709222 0.95460523 0.90128031 0.81223147 0.27671291 0.66511931
 0.82593077 0.02612047 0.54969243 0.82756276 0.48587801 0.83701452
 0.12762518 0.53681358 0.76175353 0.66372268 0.18685024 0.8903599
 0.49197732 0.88403663 0.84429273 0.53118712 0.61491323 0.39360214
 0.79287906 0.79468209 0.83302013 0.0154035  0.16983248 0.03136979
 0.27339346 0.70071315 0.99377787 0.46726614 0.09111462 0.88452373
 0.59626649 0.46430427 0.97834948 0.04889974 0.43332992 0.97076378
 0.58060796 0.81161307 0.76185409 0.5522106  0.10177788 0.58770055
 0.44828878 0.82733684 0.62118152 0.75584124 0.18495232 0.97037088
 0.25345218 0.19723938 0.28375614 0.99457677 0.24663775 0.28502668
 0.1441447  0.87491417 0.16542823 0.6931858  0.04642055 0.22674393
 0.13671054 0.23159885 0.56091964 0.0314225  0.76583677 0.0229715
 0.355531   0.03174638 0.72449175 0.48663568 0.01267042 0.6249884

Преобразовать массив из float в int

In [15]:
a = np.random.random(100)*100
print (a)
b = a.astype(int)
print (b)


[87.38155127 76.0803147  37.13995818 79.22825473  2.0414543  21.13273077
  4.53287767 44.25032301 98.58136902 48.19321963 96.45610975 97.82522447
 49.32941345  4.5918357  75.29504751  4.00662912 51.89012761 39.89864188
 28.23149032 88.93037329  8.08985678 30.91950566 93.31500358 22.67457904
 57.84291173 41.8061587  71.21791018 50.70242102 61.48175718 23.7387678
  7.88001116 67.87828347 51.29162168 31.46204384 25.03949754 61.1437769
 33.46549617 23.41640014 69.2195768  83.86776649 35.79665212 49.26421644
 48.55492365 24.70206208 54.47771189 95.27747465 14.81935718  6.04414722
 39.67688326 42.199111   98.63747284 74.14078342 95.53987696 22.03981209
 50.65542691 11.04879392 79.80819929 70.07027884  0.60401008 96.79862806
 33.43029083 48.94463574 76.99228969 94.91515328 70.15601446 93.68335105
  7.4495174   0.64109899 71.32725856  2.32721216 73.69160832 59.5430792
 77.92469722 11.06252988 96.87682609 15.18920365  4.36785955 53.57640097
 44.90161501 45.87321204 43.05647218 85.64991341 93.34

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [16]:
from scipy.spatial import distance

a = np.random.randint(1,100,(10,2))
print (a)
b = distance.cdist(a,a)
print(b)

[[ 2 79]
 [56 31]
 [37 80]
 [ 8 45]
 [55 16]
 [65 44]
 [36 95]
 [42  4]
 [30 28]
 [85 36]]
[[ 0.         72.24956747 35.0142828  34.525353   82.32860985 72.06941099
  37.57658846 85.         58.18075283 93.47726996]
 [72.24956747  0.         52.55473337 50.         15.03329638 15.8113883
  67.05221846 30.41381265 26.17250466 29.42787794]
 [35.0142828  52.55473337  0.         45.45327271 66.48308055 45.607017
  15.03329638 76.1642961  52.46903849 65.11528238]
 [34.525353   50.         45.45327271  0.         55.22680509 57.00877125
  57.30619513 53.26349594 27.80287755 77.52418977]
 [82.32860985 15.03329638 66.48308055 55.22680509  0.         29.73213749
  81.25269226 17.69180601 27.73084925 36.05551275]
 [72.06941099 15.8113883  45.607017   57.00877125 29.73213749  0.
  58.66856058 46.14108798 38.48376281 21.54065923]
 [37.57658846 67.05221846 15.03329638 57.30619513 81.25269226 58.66856058
   0.         91.19758769 67.26812024 76.69419796]
 [85.         30.41381265 76.1642961  53.2634

Случайно расположить p элементов в 2D массив

In [17]:
p = 10
# 2D array size
q = (10,10)
# array with p elements
a = np.random.randint(1,100,p)
# 2d array
b = np.zeros(q)
indices_to_change=np.random.choice(range(q[0]*q[1]), p, False)
np.put(b, indices_to_change, a)
print (b)

[[67.  0.  0.  0.  0.  0.  0.  0.  0. 63.]
 [ 0.  0.  7.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 61.  0. 76.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 40.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 79.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 86. 88.  0.]
 [ 0. 30.  0.  0.  0.  0.  0.  0.  0.  0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [18]:
mfactor = 3
a = np.array([1, 2, 3, 4, 5])
b = np.zeros(len(a) * mfactor - (mfactor - 1), dtype=int)
print(a)
print(b)
b[0::mfactor]=a
print(b)

[1 2 3 4 5]
[0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 2 0 0 3 0 0 4 0 0 5]


Найти наиболее частое значение в массиве

In [19]:
a = np.random.randint(0,10,10)
print (a)
print (np.bincount(a).argmax())

[3 1 3 7 8 1 0 3 4 0]
3


Найти n наибольших значений в массиве

In [20]:
n=5
a = np.random.randint(1,10000,1000)
print (a)
print(np.sort(a)[-5:])


[4312 7077 5680 7498 4879 2048 4246 1230 7739 3846 2648 3062 1803 8762
 3034 6728 6918 8336 2483 4132 1139 1210 1714 6512 1080 1440 4724 8571
 4299 3013 2694 7969 8649  551 9595 8051  428 8999 4606 8754 1749 4415
 1544 7156 4474 4353 3909 4517 1841 6817 7874 9515 1863 2491  460 9186
 8866 7822 4521 6707 9411 8942 7483 6916 2778 7281 6482 1093 7310 1209
 5327  427 9018 4724 8227 8701 8251 1509 3861 3669 8665 6045 5289 1824
 5029 2878 2482 9036 7942 6670 2733 5487 5890 1251 6657  997  701  264
 6285 8114 1537 2641 9011 3685 7209 9826 8427 9454 5259  657 7158 4150
 2995 8870 1714 2870 7958 8987 8135 2170  562  540 5567 8837 5453 9621
 6179 2396 2647 3552 9541 7742 9465 9595 5353 2064 3889 2613 1905 1233
 5480 6894 7931 2808 8887 2583 2813 9330  505 2941 7394  551 4716 6799
 5470 6977 5897 4423 3861 3076 1205 3784 9289 6544  696 7210 1648 5039
 6355 7496 1399 2355 4629  111 7022 7001 4820 1832   86 1943 7018 2048
 1937 8123 8385 1380 3729 9668 8333 3384 4110  849  934 3549 3965 4238
 6652 

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [21]:
import pandas as pd
food = pd.read_csv ("en.openfoodfacts.org.products.tsv", sep='\t', index_col="code")
food


/home/victor/otus_ds/otus-ds/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (0,3,5,19,20,24,25,26,27,28,36,37,38,39,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


url  \
code                                                               
3087           http://world-en.openfoodfacts.org/product/0000...   
4530           http://world-en.openfoodfacts.org/product/0000...   
4559           http://world-en.openfoodfacts.org/product/0000...   
16087          http://world-en.openfoodfacts.org/product/0000...   
16094          http://world-en.openfoodfacts.org/product/0000...   
16100          http://world-en.openfoodfacts.org/product/0000...   
16117          http://world-en.openfoodfacts.org/product/0000...   
16124          http://world-en.openfoodfacts.org/product/0000...   
16193          http://world-en.openfoodfacts.org/product/0000...   
16513          http://world-en.openfoodfacts.org/product/0000...   
16612          http://world-en.openfoodfacts.org/product/0000...   
16650          http://world-en.openfoodfacts.org/product/0000...   
16872          http://world-en.openfoodfacts.org/product/0000...   
16933          http://world-en.openfoodfacts.org/product/0000...   
17497          http://world-en.openfoodfacts.org/product/0000...   
18012          http://world-en.openfoodfacts.org/product/0000...   
18050          http://world-en.openfoodfacts.org/product/0000...   
18173          http://world-en.openfoodfacts.org/product/0000...   
18197          http://world-en.openfoodfacts.org/product/0000...   
18227          http://world-en.openfoodfacts.org/product/0000...   
18265          http://world-en.openfoodfacts.org/product/0000...   
18289          http://world-en.openfoodfacts.org/product/0000...   
18319          http://world-en.openfoodfacts.org/product/0000...   
18340          http://world-en.openfoodfacts.org/product/0000...   
18357          http://world-en.openfoodfacts.org/product/0000...   
18371          http://world-en.openfoodfacts.org/product/0000...   
18388          http://world-en.openfoodfacts.org/product/0000...   
18395          http://world-en.openfoodfacts.org/product/0000...   
18401          http://world-en.openfoodfacts.org/product/0000...   
18418          http://world-en.openfoodfacts.org/product/0000...   
...                                                          ...   
9791463741241  http://world-en.openfoodfacts.org/product/9791...   
9800120499     http://world-en.openfoodfacts.org/product/9800...   
9800801107     http://world-en.openfoodfacts.org/product/9800...   
9800895007     http://world-en.openfoodfacts.org/product/9800...   
9800895250     http://world-en.openfoodfacts.org/product/9800...   
9802735        http://world-en.openfoodfacts.org/product/9802735   
9820111458900  http://world-en.openfoodfacts.org/product/9820...   
9836654056565  http://world-en.openfoodfacts.org/product/9836...   
9847548283004  http://world-en.openfoodfacts.org/product/9847...   
98709870987    http://world-en.openfoodfacts.org/product/9870...   
9871311007     http://world-en.openfoodfacts.org/product/9871...   
9876567898765  http://world-en.openfoodfacts.org/product/9876...   
988639          http://world-en.openfoodfacts.org/product/988639   
9900000000233  http://world-en.openfoodfacts.org/product/9900...   
9900010011557  http://world-en.openfoodfacts.org/product/9900...   
9901198001583  http://world-en.openfoodfacts.org/product/9901...   
9901942000794  http://world-en.openfoodfacts.org/product/9901...   
99044169       http://world-en.openfoodfacts.org/product/9904...   
9906410000009  http://world-en.openfoodfacts.org/product/9906...   
9908278636246  http://world-en.openfoodfacts.org/product/9908...   
99111250       http://world-en.openfoodfacts.org/product/9911...   
9918           http://world-en.openfoodfacts.org/product/9918...   
9935010000003  http://world-en.openfoodfacts.org/product/9935...   
99410148       http://world-en.openfoodfacts.org/product/9941...   
9948282780603  http://world-en.openfoodfacts.org/product/9948...   
99567453       http://world-en.openfoodfacts.org/product/9956...   
9970229501521  http://world-en.openfoodfacts.org/

Посмотреть первые 5 записей

In [22]:
food.head()

url  \
code                                                       
3087   http://world-en.openfoodfacts.org/product/0000...   
4530   http://world-en.openfoodfacts.org/product/0000...   
4559   http://world-en.openfoodfacts.org/product/0000...   
16087  http://world-en.openfoodfacts.org/product/0000...   
16094  http://world-en.openfoodfacts.org/product/0000...   

                          creator   created_t      created_datetime  \
code                                                                  
3087   openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
4530              usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
4559              usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
16087             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
16094             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

      last_modified_t last_modified_datetime                    product_name  \
code                                                                           
3087       1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
4530       1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
4559       1489069957   2017-03-09T14:32:37Z                         Peanuts   
16087      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
16094      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

      generic_name quantity packaging  ... fruits-vegetables-nuts_100g  \
code                                   ...                               
3087           NaN      1kg       NaN  ...                         NaN   
4530           NaN      NaN       NaN  ...                         NaN   
4559           NaN      NaN       NaN  ...                         NaN   
16087          NaN      NaN       NaN  ...                         NaN   
16094          NaN      NaN       NaN  ...                         NaN   

      fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
code                                                                          
3087                                   NaN                              NaN   
4530                                   NaN                              NaN   
4559                                   NaN                              NaN   
16087                                  NaN                              NaN   
16094                                  NaN                              NaN   

      cocoa_100g chlorophyl_100g carbon-footprint_100g  \
code                                                     
3087         NaN             NaN                   NaN   
4530         NaN             NaN                   NaN   
4559         NaN             NaN                   NaN   
16087        NaN             NaN                   NaN   
16094        NaN             NaN                   NaN   

      nutrition-score-fr_100g nutrition-score-uk_100g glycemic-index_100g  \
code                                                                        
3087                      NaN                     NaN                 NaN   
4530                     14.0                    14.0                 NaN   
4559                      0.0                     0.0                 NaN   
16087                    12.0                    12.0                 NaN   
16094                     NaN                     NaN                 NaN   

      water-hardness_100g  
code                       
3087                  NaN  
4530                  NaN  
4559                  NaN  
16087                 NaN  
16094                 NaN  

[5 rows x 162 columns]

Сколько наблюдений в наборе данных?


In [23]:
food.shape[0]

356027

Сколько столбцов в наборе данных?

In [24]:
food.shape[1]

162

Напечатайте все названия столбцов

In [25]:
for column in food.columns:    
    print ("%s" % column)

url
creator
created_t
created_datetime
last_modified_t
last_modified_datetime
product_name
generic_name
quantity
packaging
packaging_tags
brands
brands_tags
categories
categories_tags
categories_en
origins
origins_tags
manufacturing_places
manufacturing_places_tags
labels
labels_tags
labels_en
emb_codes
emb_codes_tags
first_packaging_code_geo
cities
cities_tags
purchase_places
stores
countries
countries_tags
countries_en
ingredients_text
allergens
allergens_en
traces
traces_tags
traces_en
serving_size
no_nutriments
additives_n
additives
additives_tags
additives_en
ingredients_from_palm_oil_n
ingredients_from_palm_oil
ingredients_from_palm_oil_tags
ingredients_that_may_be_from_palm_oil_n
ingredients_that_may_be_from_palm_oil
ingredients_that_may_be_from_palm_oil_tags
nutrition_grade_uk
nutrition_grade_fr
pnns_groups_1
pnns_groups_2
states
states_tags
states_en
main_category
main_category_en
image_url
image_small_url
energy_100g
energy-from-fat_100g
fat_100g
saturated-fat_100g
-butyric-a

Какое название у 105 столбца?

In [26]:
print(food.columns[104])

-fructose_100g


Какой тип наблюдений в 105 столбце?

In [27]:
print(food.dtypes[104])
food[food.columns[104]].unique()

float64


array([     nan, 4.30e+01, 2.50e+01, 2.90e+01, 2.80e+01, 1.80e+01,
       1.00e+02, 2.60e+01, 6.39e+01, 1.01e+02, 3.15e+01, 2.40e+00,
       5.51e+01, 6.00e+01, 6.90e+01, 9.00e-01, 3.00e+00, 1.00e-01,
       8.00e+00, 6.00e+00, 2.00e-01, 4.70e+01, 1.50e+00, 5.00e+00,
       0.00e+00, 1.30e+00, 1.10e+00, 3.00e-01, 3.51e+01, 2.30e+00,
       7.00e+01, 5.00e-01])

Тип: непрерывная переменная

Как проиндексирован набор данных?

In [28]:
food.index


Index([           3087,            4530,            4559,           16087,
                 16094,           16100,           16117,           16124,
                 16193,           16513,
       ...
            '99111250',          '9918', '9935010000003',      '99410148',
       '9948282780603',      '99567453', '9970229501521', '9977471758307',
       '9980282863788',  '999990026839'],
      dtype='object', name='code', length=356027)

Каково значение имени продукта в 19-м наблюдении?

In [29]:
food.iloc[18]["product_name"]

'Lotus Organic Brown Jasmine Rice'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [30]:
import requests

url="https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep='\t', converters={"item_price":lambda x: float(x.replace('$', ''))})

chipo.head(10)




order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description  item_price  
0                                                NaN        2.39  
1                                       [Clementine]        3.39  
2                                            [Apple]        3.39  
3                                                NaN        2.39  
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98  
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...       10.98  
6                                                NaN        1.69  
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.75  
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...        9.25  
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...        9.25

Как много продуктов стоят более чем $10.00?

In [31]:
chipo[chipo['item_price'] > 10].shape[0]

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [32]:
chipo[['item_name', 'item_price']]

item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
5                              Chicken Bowl       10.98
6                             Side of Chips        1.69
7                             Steak Burrito       11.75
8                          Steak Soft Tacos        9.25
9                             Steak Burrito        9.25
10                      Chips and Guacamole        4.45
11                     Chicken Crispy Tacos        8.75
12                       Chicken Soft Tacos        8.75
13                             Chicken Bowl       11.25
14                      Chips and Guacamole        4.45
15    Chips and Tomatillo-Green Chili Salsa        2.39
16                          Chicken Burrito        8.49
17                          Chicken Burrito        8.49
18                              Canned Soda        2.18
19                             Chicken Bowl        8.75
20                      Chips and Guacamole        4.45
21                         Barbacoa Burrito        8.99
22                         Nantucket Nectar        3.39
23                          Chicken Burrito       10.98
24                                     Izze        3.39
25             Chips and Fresh Tomato Salsa        2.39
26                             Chicken Bowl        8.49
27                         Carnitas Burrito        8.99
28                              Canned Soda        1.09
29                          Chicken Burrito        8.49
...                                     ...         ...
4592                       Barbacoa Burrito       11.75
4593                          Carnitas Bowl       11.75
4594                          Barbacoa Bowl       11.75
4595                           Chicken Bowl        8.75
4596                    Chips and Guacamole        4.45
4597                      Canned Soft Drink        1.25
4598                          Bottled Water        1.50
4599                           Chicken Bowl        8.75
4600                    Chips and Guacamole        4.45
4601                      Canned Soft Drink        1.25
4602                       Barbacoa Burrito        9.25
4603                       Barbacoa Burrito        9.25
4604                           Chicken Bowl        8.75
4605                    Chips and Guacamole        4.45
4606                      Canned Soft Drink        1.25
4607                          Steak Burrito       11.75
4608                         Veggie Burrito       11.25
4609                      Canned Soft Drink        1.25
4610                          Steak Burrito       11.75
4611                         Veggie Burrito       11.25
4612                          Carnitas Bowl        9.25
4613                                  Chips        2.15
4614                          Bottled Water        1.50
4615                     Chicken Soft Tacos        8.75
4616                    Chips and Guacamole        4.45
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

Отсортировать по имени предмета

In [33]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      1664         1  6 Pack Soft Drink   
4174      1666         1  6 Pack Soft Drink   
4527      1800         1  6 Pack Soft Drink   
4522      1798         1  6 Pack Soft Drink   
3806      1525         1  6 Pack Soft Drink   
2389       949         1  6 Pack Soft Drink   
3132      1248         1  6 Pack Soft Drink   
3141      1253         1  6 Pack Soft Drink   
639        264         1  6 Pack Soft Drink   
1026       422         1  6 Pack Soft Drink   
...        ...       ...                ...   
2996      1192         1       Veggie Salad   
3163      1263         1       Veggie Salad   
4084      1635         1       Veggie Salad   
1694       686         1       Veggie Salad   
2756      1094         1       Veggie Salad   
4201      1677         1  Veggie Salad Bowl   
1884       760         1  Veggie Salad Bowl   
455        195         1  Veggie Salad Bowl   
3223      1289         1  Veggie Salad Bowl   
2223       896         1  Veggie Salad Bowl   
2269       913         1  Veggie Salad Bowl   
4541      1805         1  Veggie Salad Bowl   
3293      1321         1  Veggie Salad Bowl   
186         83         1  Veggie Salad Bowl   
960        394         1  Veggie Salad Bowl   
1316       536         1  Veggie Salad Bowl   
2156       869         1  Veggie Salad Bowl   
4261      1700         1  Veggie Salad Bowl   
295        128         1  Veggie Salad Bowl   
4573      1818         1  Veggie Salad Bowl   
2683      1066         1  Veggie Salad Bowl   
496        207         1  Veggie Salad Bowl   
4109      1646         1  Veggie Salad Bowl   
738        304         1  Veggie Soft Tacos   
3889      1559         2  Veggie Soft Tacos   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description  item_price  
3389                                        [Diet Coke]       12.98  
341                                         [Diet Coke]        6.49  
1849                                             [Coke]        6.49  
1860                                        [Diet Coke]        6.49  
2713                                             [Coke]        6.49  
3422                                             [Coke]        6.49  
553                                         [Diet Coke]        6.49  
1916                                        [Diet Coke]        6.49  
1922                                             [Coke]        6.49  
1937                                        [Diet Coke]        6.49  
3836                                             [Coke]        6.49  
298                                            [Sprite]        6.49  
1976                                        [Diet Coke]        6.49  
1167                                             [Coke]        6.49  
3875                                     

Сколько было заказано самого дорогого предмета?

In [34]:
chipo[chipo['item_price'] == chipo['item_price'].max()]['quantity'].sum()

15

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [35]:
chipo[chipo['item_name'] == "Veggie Salad Bowl"]['quantity'].count()

18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [36]:
chipo[(chipo['quantity'] > 1) & (chipo['item_name'] == "Canned Soda")].shape[0]

20